#
# Copyright 2018, TOTVS S.A.
# All rights reserved.
#

# defaul shell
SHELL = /bin/bash

# ensure that java path is configured
JAVA_HOME ?= /usr/lib/jvm/java-8-oracle

# Rule "maven:build"
.PHONY: maven\:build
.SILENT: maven\:build
maven\:build:
	# produce a failure return code if any command return error \
	set -eo pipefail; \
	mvn clean install -f pom.xml -U -Pintegration-test -DdatabaseProfile=$(DATABASE);

# Rule "pre_build"
.PHONY: pre_build
.SILENT: pre_build
pre_build:
	# produce a failure return code if any command return error \
	set -eo pipefail;

# Rule "build"
.PHONY: build
.SILENT: build
build:
	# produce a failure return code if any command return error \
	set -eo pipefail; \
	make maven:build;

# Rule "post_build"
.PHONY: post_build
.SILENT: post_build
post_build:
	# produce a failure return code if any command return error \
	set -eo pipefail;